/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti.projhallinta;

import projekti.login.LoginUI;

/**
 *
 * @author s1200508
 */
public class ProjektiHallintaUI extends javax.swing.JFrame {

    /**
     * Creates new form ProjektiHallinta
     */
    public ProjektiHallintaUI() {
        this.setTitle("Projektinhallinta");

        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        muokkaaTyontekijoitaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        projektitTextArea = new javax.swing.JTextArea();
        muokkaaVaiheitaButton = new javax.swing.JButton();
        projektinTiedotButton = new javax.swing.JButton();
        uusiProjektiButton = new javax.swing.JButton();
        kirjauduUlosButton = new javax.swing.JButton();
        lopetaButton = new javax.swing.JButton();
        projektiFilterComboBox = new javax.swing.JComboBox();
        kukaLisasTanTurhanPaskanSyytanMiroaTjasu = new javax.swing.JLabel();
        muokkaaAsiakkaitaButton = new javax.swing.JButton();
        kukaLisasTanTurhanPaskanSyytanFronsiaTjasu = new javax.swing.JMenuBar();
        katsoRiviYlospain = new javax.swing.JMenu();
        katsoKaksiRiviaYlospain = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        muokkaaTyontekijoitaButton.setText("Muokkaa työntekijöitä");
        muokkaaTyontekijoitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuokkaaTyontekijoitaActionPerformed(evt);
                avaaMuokkaatyontekijoita();
            }
        });

        projektitTextArea.setColumns(20);
        projektitTextArea.setRows(5);
        jScrollPane1.setViewportView(projektitTextArea);

        muokkaaVaiheitaButton.setText("Muokkaa vaiheita");
        muokkaaVaiheitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuokkaaVaiheitaActionPerformed(evt);
                avaaMuokkaaVaiheita();
            }
        });

        projektinTiedotButton.setText("Projektin muokkaus");
        projektinTiedotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektinTiedotActionPerformed(evt);
                avaaProjektinMuokkaus();
            }
        });

        uusiProjektiButton.setText("Uusi projekti");
        uusiProjektiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiProjektiActionPerformed(evt);
                avaaProjektinLisays();
            }
        });

        kirjauduUlosButton.setText("Kirjaudu ulos");
        kirjauduUlosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirjauduUlosActionPerformed(evt);
                avaaKirjauduUlos();
                


            }
        });

        lopetaButton.setText("Lopeta");
        lopetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaActionPerformed(evt);
                System.exit(0);
                
            }
        });

        projektiFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        projektiFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektiFilterActionPerformed(evt);
            }
        });

        muokkaaAsiakkaitaButton.setText("Muokkaa asiakkaita");
        muokkaaAsiakkaitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muokkaaAsiakkaitaActionPerformed(evt);
            }
        });

        katsoRiviYlospain.setText("File");
        kukaLisasTanTurhanPaskanSyytanFronsiaTjasu.add(katsoRiviYlospain);

        katsoKaksiRiviaYlospain.setText("Edit");
        kukaLisasTanTurhanPaskanSyytanFronsiaTjasu.add(katsoKaksiRiviaYlospain);

        setJMenuBar(kukaLisasTanTurhanPaskanSyytanFronsiaTjasu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kukaLisasTanTurhanPaskanSyytanMiroaTjasu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(projektiFilterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(muokkaaVaiheitaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(muokkaaAsiakkaitaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(muokkaaTyontekijoitaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projektinTiedotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uusiProjektiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kirjauduUlosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lopetaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(muokkaaTyontekijoitaButton)
                            .addComponent(projektiFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kukaLisasTanTurhanPaskanSyytanMiroaTjasu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muokkaaVaiheitaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projektinTiedotButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muokkaaAsiakkaitaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiProjektiButton)
                    .addComponent(kirjauduUlosButton)
                    .addComponent(lopetaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>  
    
    private void avaaProjektinLisays(){
    	this.dispose();
		ProjektinlisaysUI ikkuna = new ProjektinlisaysUI();
		ikkuna.setVisible(true);
    }
    private void avaaProjektinMuokkaus(){
    	this.dispose();
		ProjektinMuokkausUI ikkuna = new ProjektinMuokkausUI();
		ikkuna.setVisible(true);
    }
    private void avaaMuokkaatyontekijoita(){
    	this.dispose();
		TyontekijoidenHallintaUI ikkuna = new TyontekijoidenHallintaUI();
		ikkuna.setVisible(true);
    }
    private void avaaMuokkaaVaiheita(){
    	this.dispose();
		VaiheidenHallintaUI ikkuna = new VaiheidenHallintaUI();
		ikkuna.setVisible(true);
    }

    private void avaaKirjauduUlos(){
    		LoginUI ikkuna = new LoginUI();
    		ikkuna.setVisible(true);
    		this.dispose();
        }
    

    private void uusiProjektiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void MuokkaaTyontekijoitaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void MuokkaaVaiheitaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void projektinTiedotActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void lopetaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void kirjauduUlosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void muokkaaAsiakkaitaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void projektiFilterActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektiHallintaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektiHallintaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektiHallintaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektiHallintaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektiHallintaUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton muokkaaTyontekijoitaButton;
    private javax.swing.JButton muokkaaVaiheitaButton;
    private javax.swing.JLabel kukaLisasTanTurhanPaskanSyytanMiroaTjasu;
    private javax.swing.JMenu katsoRiviYlospain;
    private javax.swing.JMenu katsoKaksiRiviaYlospain;
    private javax.swing.JMenuBar kukaLisasTanTurhanPaskanSyytanFronsiaTjasu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea projektitTextArea;
    private javax.swing.JButton kirjauduUlosButton;
    private javax.swing.JButton lopetaButton;
    private javax.swing.JButton muokkaaAsiakkaitaButton;
    private javax.swing.JComboBox projektiFilterComboBox;
    private javax.swing.JButton projektinTiedotButton;
    private javax.swing.JButton uusiProjektiButton;
    // End of variables declaration                   
}
